#!/usr/bin/env bash
# =============================================================================
# scripts/ci/propagate_project_ci.sh
#
# Installs the reusable Yantra4D project CI workflow into every public project
# repo under madfam-org. Requires the GitHub CLI (`gh`) to be installed and
# authenticated with sufficient repo-scoped permissions.
#
# Usage:
#   ./scripts/ci/propagate_project_ci.sh [--dry-run] [--secret-only] [--force]
#
# Flags:
#   --dry-run      Print actions but don't apply them
#   --secret-only  Only set DISPATCH_TOKEN secrets, skip workflow file writes
#   --force        Overwrite existing workflow files in project repos
#
# Prerequisites:
#   gh auth login (with repo + workflow scopes)
#   DISPATCH_TOKEN env var: a GitHub PAT with repo + writes access to madfam-org/yantra4d
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
GITMODULES="${ROOT_DIR}/.gitmodules"
REUSABLE_WORKFLOW_REF="madfam-org/yantra4d/.github/workflows/project-ci-reusable.yml@main"

# ---- Argument parsing --------------------------------------------------------
DRY_RUN=false
SECRET_ONLY=false
FORCE=false

for arg in "$@"; do
  case $arg in
    --dry-run)    DRY_RUN=true ;;
    --secret-only) SECRET_ONLY=true ;;
    --force)      FORCE=true ;;
    *)            echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

# ---- Validation --------------------------------------------------------------
if [ -z "${DISPATCH_TOKEN:-}" ]; then
  echo "ERROR: DISPATCH_TOKEN env var is required."
  echo "  Create a PAT at https://github.com/settings/tokens with 'repo' + 'workflow' scopes"
  echo "  and export DISPATCH_TOKEN=<your-token>"
  exit 1
fi

if ! command -v gh &>/dev/null; then
  echo "ERROR: GitHub CLI (gh) is not installed. Install from https://cli.github.com"
  exit 1
fi

# ---- Read slugs from .gitmodules, filter to projects/ only ------------------
mapfile -t ALL_SLUGS < <(
  grep -E '^\s*path\s*=\s*projects/' "${GITMODULES}" \
  | sed 's|.*projects/||' \
  | tr -d '[:space:]'
)

# Private repos to skip (tablaco uses update=none)
SKIP_REPOS=("tablaco")

echo "=================================================="
echo "Yantra4D Per-Project CI Propagation"
echo "  Reusable workflow: ${REUSABLE_WORKFLOW_REF}"
echo "  Total project submodules found: ${#ALL_SLUGS[@]}"
echo "  Dry run: ${DRY_RUN}"
echo "=================================================="

SUCCESS=0
SKIPPED=0
FAILED=0

for SLUG in "${ALL_SLUGS[@]}"; do
  REPO="madfam-org/${SLUG}"

  # Skip private/excluded repos
  if [[ " ${SKIP_REPOS[*]} " =~ " ${SLUG} " ]]; then
    echo "[SKIP]  ${REPO} — listed in SKIP_REPOS (private)"
    ((SKIPPED++)) || true
    continue
  fi

  echo ""
  echo "---- Processing: ${REPO} ----"

  # ---- Set DISPATCH_TOKEN secret on the project repo -----------------------
  if [ "${DRY_RUN}" = false ]; then
    if echo "${DISPATCH_TOKEN}" | gh secret set DISPATCH_TOKEN \
        --repo "${REPO}" \
        --body - 2>/dev/null; then
      echo "[OK]    Set DISPATCH_TOKEN secret on ${REPO}"
    else
      echo "[WARN]  Could not set secret on ${REPO} (may lack permission — skipping)"
      ((FAILED++)) || true
      continue
    fi
  else
    echo "[DRY]   Would set DISPATCH_TOKEN secret on ${REPO}"
  fi

  if [ "${SECRET_ONLY}" = true ]; then
    ((SUCCESS++)) || true
    continue
  fi

  # ---- Generate the caller workflow file content ---------------------------
  WORKFLOW_CONTENT="# Auto-generated by madfam-org/yantra4d scripts/ci/propagate_project_ci.sh
# Validates this project against the Yantra4D commons standards and auto-bumps
# the submodule SHA in yantra4d when main branch passes CI.
name: Yantra4D Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  project-ci:
    uses: ${REUSABLE_WORKFLOW_REF}
    secrets:
      DISPATCH_TOKEN: \${{ secrets.DISPATCH_TOKEN }}
"

  # ---- Check if workflow already exists ------------------------------------
  EXISTING=$(gh api \
    "/repos/${REPO}/contents/.github/workflows/ci.yml" \
    --jq '.sha' 2>/dev/null || echo "")

  if [ -n "${EXISTING}" ] && [ "${FORCE}" = false ]; then
    echo "[SKIP]  ${REPO} already has .github/workflows/ci.yml (use --force to overwrite)"
    ((SKIPPED++)) || true
    continue
  fi

  # ---- Write workflow file via GitHub API ----------------------------------
  ENCODED_CONTENT=$(echo "${WORKFLOW_CONTENT}" | base64 | tr -d '\n')
  COMMIT_MSG="ci: add Yantra4D project CI workflow [auto-propagated]"

  if [ "${DRY_RUN}" = false ]; then
    if [ -n "${EXISTING}" ]; then
      # Update existing file
      gh api --method PUT \
        "/repos/${REPO}/contents/.github/workflows/ci.yml" \
        --field message="${COMMIT_MSG}" \
        --field content="${ENCODED_CONTENT}" \
        --field sha="${EXISTING}" \
        --silent 2>/dev/null && \
        echo "[OK]    Updated .github/workflows/ci.yml in ${REPO}" || \
        { echo "[FAIL]  Failed to update workflow in ${REPO}"; ((FAILED++)) || true; continue; }
    else
      # Create new file
      gh api --method PUT \
        "/repos/${REPO}/contents/.github/workflows/ci.yml" \
        --field message="${COMMIT_MSG}" \
        --field content="${ENCODED_CONTENT}" \
        --silent 2>/dev/null && \
        echo "[OK]    Created .github/workflows/ci.yml in ${REPO}" || \
        { echo "[FAIL]  Failed to create workflow in ${REPO}"; ((FAILED++)) || true; continue; }
    fi
  else
    echo "[DRY]   Would write .github/workflows/ci.yml to ${REPO}"
  fi

  ((SUCCESS++)) || true
done

# ---- Summary -----------------------------------------------------------------
echo ""
echo "=================================================="
echo "Propagation complete."
echo "  Success:  ${SUCCESS}"
echo "  Skipped:  ${SKIPPED}"
echo "  Failed:   ${FAILED}"
echo "=================================================="

if [ "${FAILED}" -gt 0 ]; then
  echo "WARNING: ${FAILED} repo(s) failed. Check output above."
  exit 1
fi
