/**
 * `public/models/manifest.json` — which cartridges have a pre-rendered mesh and
 * which file to load for each.
 *
 * Two shapes are read:
 *   v1 (2026-03, `scripts/prerender-carousel.sh`): `{ generated, models: [{ slug, size }] }`,
 *       one uncompressed `<slug>.glb` per entry.
 *   v2 (2026-09, `scripts/dev/optimize-commons-models.mjs`): adds `version: 2`,
 *       per-slug `lod1` / `lod0` (meshopt-compressed, budgeted) and optional
 *       animation `frames`. `size` is kept on every entry so v1 readers still work.
 *
 * Both are tolerated because the manifest is regenerated by a pipeline that
 * ships independently of the page; the page must not break the day either
 * side moves first.
 */

export interface ManifestFile {
  file: string;
  bytes: number;
  triangles?: number;
}

export interface ManifestFrame extends ManifestFile {
  animation: string;
  index: number;
}

export interface ManifestModel {
  slug: string;
  /** v1 compatibility: bytes of the smallest available file. */
  size?: number;
  lod1?: ManifestFile;
  lod0?: ManifestFile;
  frames?: ManifestFrame[];
}

export interface ModelsManifest {
  version?: number;
  generated?: string;
  models: ManifestModel[];
}

export type Lod = 'lod1' | 'lod0';

export const MODELS_BASE = '/models/';

/** Slugs that have any mesh at all, in manifest order. */
export function modelledSlugs(manifest: ModelsManifest | null | undefined): string[] {
  if (!manifest || !Array.isArray(manifest.models)) return [];
  return manifest.models.filter((m) => m && typeof m.slug === 'string').map((m) => m.slug);
}

/**
 * The URL to load for a slug at the requested LOD. Falls back from lod0 to
 * lod1 to the v1 `<slug>.glb`; null when the slug has no mesh.
 */
export function modelUrl(
  manifest: ModelsManifest | null | undefined,
  slug: string,
  lod: Lod = 'lod1',
): string | null {
  const entry = manifest?.models?.find((m) => m && m.slug === slug);
  if (!entry) return null;
  const preferred = lod === 'lod0' ? entry.lod0 ?? entry.lod1 : entry.lod1 ?? entry.lod0;
  if (preferred?.file) return `${MODELS_BASE}${preferred.file}`;
  return `${MODELS_BASE}${slug}.glb`;
}

/** True when any file in the manifest needs the meshopt decoder (v2). */
export function usesMeshopt(manifest: ModelsManifest | null | undefined): boolean {
  return (manifest?.version ?? 1) >= 2;
}
