"""Shared core for the ceq coverage driver + tracker.

Two scripts sit on top of this module and must agree on every byte:

  - ``scripts/dev/ceq_backfill.py``  — mints hyperobject cards/textures via ceq
    and records them in the sidecar.
  - ``scripts/qa/ceq_coverage.py``   — reports N/M coverage from the sidecar.

Everything they share lives here: the catalog reader (always *dynamic* — the
commons is mid-growth and a hardcoded count goes stale within a day), the
payload mapping from a cartridge to a ceq render request, the payload hash
(recomputed the way ceq computes it, so resume is exact), and the sidecar
schema + deterministic serializer.

## The payload hash — why we recompute it locally

ceq's ``/v1/render/*`` is content-addressed: ``render_hash(template, data,
template_version)`` is ``sha256`` over

    json.dumps({"template": t, "version": v, "data": d},
               sort_keys=True, separators=(",", ":"), default=str)

(ceq ``apps/api/src/ceq_api/render/hash.py``). Recomputing that locally lets the
backfill answer "has this exact card already been rendered?" from the sidecar
alone — no network call, no credential, no rate budget. That is what makes the
driver resumable and what makes ``--dry-run`` genuinely informative.

The hash includes ``template_version``. We do NOT guess it: the driver reads it
from ``GET /v1/render/templates`` and stores it in the sidecar entry, so a
template version bump shows up as a payload-hash change and the affected slugs
re-render on the next pass instead of silently serving stale art.

## Real thumbnails vs placeholders

``apps/{studio,landing}/public/projects`` holds two populations, and the
difference is *content*, not filename: real renders are RIFF/WEBP (or PNG)
rasters produced by ``scripts/dev/render_commons_thumbnails.py``; placeholders
are SVG tiles from ``scripts/dev/generate-placeholder-thumbnails.py``. That
generator can also write SVG bytes into a ``.webp`` filename
(``--emit-webp-names``), so extension-sniffing lies. We sniff magic bytes.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]

CATALOG_PATH = REPO / "docs" / "commons-catalog.json"
SIDECAR_PATH = REPO / "docs" / "ceq-coverage.json"
PROJECTS_DIR = REPO / "projects"
THUMB_DIRS = (
    REPO / "apps" / "studio" / "public" / "projects",
    REPO / "apps" / "landing" / "public" / "projects",
)

SIDECAR_SCHEMA_VERSION = "ceq_coverage_v1"

#: Asset kinds this driver tracks. ``card`` is the hyperobject trading-card
#: style render; ``texture`` is the FLUX-backed material/texture plate.
ASSET_KINDS = ("card", "texture")

#: Default ceq template per asset kind. Configurable (``--card-template`` /
#: ``--texture-template``) because the templates land on ceq's own schedule and
#: a rename must not require a code change here.
DEFAULT_TEMPLATES = {
    "card": "hyperobject-card",
    "texture": "hyperobject-texture",
}

#: Raster magic bytes → a real rendered thumbnail (not a placeholder tile).
_RASTER_MAGIC = (
    (b"RIFF", 0),          # WebP container (bytes 8..12 are "WEBP")
    (b"\x89PNG\r\n\x1a\n", 0),
    (b"\xff\xd8\xff", 0),  # JPEG
)

#: Domain → accent hex. Mirrors the hue pairs in
#: ``scripts/dev/generate-placeholder-thumbnails.py`` so a ceq card and the
#: gallery placeholder it replaces read as the same family, not two palettes.
DOMAIN_ACCENT = {
    "household": "#2f9e9e",
    "industrial": "#d98324",
    "commercial": "#8b5cf6",
    "medical": "#2fa36b",
    "infrastructure": "#3b6fd4",
    "hybrid": "#e0559b",
    "soft-robotics": "#7ab52f",
    "wearable": "#c2568f",
    "uncategorized": "#5b7085",
}
FALLBACK_ACCENT = DOMAIN_ACCENT["uncategorized"]

_HEX_RE = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")


class CoverageError(RuntimeError):
    """A malformed input the operator must fix (bad sidecar, bad catalog)."""


# ──────────────────────────────────────────────────────────────────────────────
# Catalog
# ──────────────────────────────────────────────────────────────────────────────

def load_catalog(path: Path | None = None) -> dict[str, Any]:
    """Read ``docs/commons-catalog.json``.

    The catalog is regenerated by ``scripts/qa/generate_commons_catalog.py`` and
    grows continuously (400 cartridges at the time of writing, a fourth-hundred
    merge in flight). Every count in this module derives from what is read here
    — nothing about the commons size is baked in.
    """
    path = path or CATALOG_PATH
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise CoverageError(f"commons catalog not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise CoverageError(f"commons catalog is not valid JSON ({path}): {exc}") from exc
    if not isinstance(raw, dict) or not isinstance(raw.get("cartridges"), list):
        raise CoverageError(f"commons catalog has no cartridges[] array: {path}")
    return raw


def catalog_entries(catalog: dict[str, Any]) -> list[dict[str, Any]]:
    """Cartridge entries, sorted by slug, skipping entries without a slug."""
    entries = [c for c in catalog["cartridges"] if isinstance(c, dict) and c.get("slug")]
    return sorted(entries, key=lambda c: str(c["slug"]))


def load_manifest(slug: str, projects_dir: Path | None = None) -> dict[str, Any]:
    """A cartridge's ``project.json``, or ``{}`` when it is not on disk.

    Missing is not fatal: a catalog entry can describe a cartridge whose
    submodule is not checked out, and the catalog itself carries everything the
    card payload structurally requires. The manifest only enriches (colors,
    description, thumbnail declaration).
    """
    projects_dir = projects_dir or PROJECTS_DIR
    mpath = projects_dir / slug / "project.json"
    try:
        return json.loads(mpath.read_text(encoding="utf-8"))
    except (FileNotFoundError, NotADirectoryError):
        return {}
    except json.JSONDecodeError as exc:
        raise CoverageError(f"{slug}: project.json is not valid JSON: {exc}") from exc


# ──────────────────────────────────────────────────────────────────────────────
# Thumbnail classification (real raster vs SVG placeholder vs absent)
# ──────────────────────────────────────────────────────────────────────────────

def _is_raster(path: Path) -> bool:
    """True when the file's *content* is a raster image.

    Deliberately content-sniffed: the placeholder generator's
    ``--emit-webp-names`` mode writes SVG markup into ``<slug>.webp``, so a
    ``.webp`` suffix proves nothing.
    """
    try:
        head = path.read_bytes()[:16]
    except OSError:
        return False
    return any(head.startswith(magic) for magic, _ in _RASTER_MAGIC)


def thumbnail_status(slug: str, thumb_dirs: tuple[Path, ...] | None = None) -> str:
    """``"real"`` | ``"placeholder"`` | ``"missing"`` for one slug.

    ``real`` wins over ``placeholder``: a cartridge that has both a rendered
    raster and a leftover SVG tile is covered by the raster (the frontend only
    falls back to ``.svg`` when the raster 404s).
    """
    dirs = thumb_dirs if thumb_dirs is not None else THUMB_DIRS
    found_any = False
    for d in dirs:
        for ext in (".webp", ".png", ".jpg", ".jpeg", ".svg"):
            p = d / f"{slug}{ext}"
            if not p.is_file():
                continue
            found_any = True
            if _is_raster(p):
                return "real"
    return "placeholder" if found_any else "missing"


# ──────────────────────────────────────────────────────────────────────────────
# Payload mapping — cartridge → ceq render `data`
# ──────────────────────────────────────────────────────────────────────────────

def _text(value: Any, lang: str = "en") -> str:
    """Flatten a manifest i18n blob (``{"en": …, "es": …}``) or a bare string."""
    if isinstance(value, dict):
        picked = value.get(lang) or next((v for v in value.values() if isinstance(v, str)), "")
        return str(picked).strip()
    if isinstance(value, str):
        return value.strip()
    return ""


def manifest_accent(manifest: dict[str, Any]) -> str | None:
    """First valid hex colour declared by the cartridge's parts, if any.

    Cartridges carry colour in ``parts[].default_color`` (998 occurrences across
    the commons); nothing else in the manifest is a palette. When a cartridge
    declares one we prefer it over the domain accent, so a card looks like the
    object the studio shows.
    """
    for part in manifest.get("parts") or []:
        if not isinstance(part, dict):
            continue
        for key in ("default_color", "color"):
            value = part.get(key)
            if isinstance(value, str) and _HEX_RE.match(value.strip()):
                return value.strip().lower()
    return None


def accent_for(entry: dict[str, Any], manifest: dict[str, Any]) -> str:
    """Card accent: manifest colour → domain accent → neutral fallback."""
    return (
        manifest_accent(manifest)
        or DOMAIN_ACCENT.get(str(entry.get("domain") or ""), FALLBACK_ACCENT)
    )


def _clip(text: str, limit: int) -> str:
    """Trim to ``limit`` characters on a word boundary with an ellipsis.

    Card copy is drawn into a fixed 512x768 plate; sending a 900-character
    societal-benefit paragraph would render as an overflowing block *and* would
    make the payload hash churn on every copy edit deep in a description.
    """
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0].rstrip(" ,;:.")
    return (cut or text[: limit - 1]) + "…"


def card_payload(entry: dict[str, Any], manifest: dict[str, Any] | None = None) -> dict[str, Any]:
    """Build the ``hyperobject-card`` ``data`` block for one cartridge.

    Structural fields come from the catalog entry (it is the generated, always-
    current projection of every manifest); ``description`` and ``accent`` are
    enriched from the manifest when it is checked out. Absent optional fields
    are *omitted*, never sent as empty strings — an omitted key and a key set to
    "" are different payload hashes, and omission keeps the hash stable for the
    many cartridges that simply have no such data.

    ``silhouette`` is intentionally never emitted. The task allowed a coarse
    polyline extracted from existing thumbnail SVGs, but those SVGs are
    *placeholder tiles*: their only vector content is a generic glyph selected
    per ``geometry_type`` (the same circle-in-circle for every ``socket``
    cartridge), not an outline of the object. Shipping that as a silhouette
    would encode a lie about the geometry into a content-addressed asset. When a
    real 2-D outline source exists (an SVG projection from the render pipeline),
    add it here and the hash change will re-render every card exactly once.
    """
    manifest = manifest or {}
    proj = manifest.get("project") if isinstance(manifest.get("project"), dict) else {}

    slug = str(entry["slug"])
    domain = str(entry.get("domain") or "") or None
    interfaces = entry.get("cdg_interfaces")
    n_interfaces = len(interfaces) if isinstance(interfaces, list) else 0

    data: dict[str, Any] = {
        "slug": slug,
        "title": _clip(_text(entry.get("name")) or _text(proj.get("name")) or slug, 60),
    }
    if domain:
        data["domain"] = domain
        data["subtitle"] = domain

    description = _text(proj.get("description")) or _text(entry.get("societal_benefit"))
    if description:
        data["description"] = _clip(description, 220)

    # The hyperobject block — the part that makes this a *commons* card rather
    # than a generic thumbnail. Emitted only when there is something to say.
    hyperobject: dict[str, Any] = {}
    if n_interfaces:
        hyperobject["cdg_interfaces"] = n_interfaces
    provenance = _text(entry.get("commons_license"))
    if provenance:
        hyperobject["provenance"] = provenance
    engines = entry.get("engines")
    if isinstance(engines, list) and engines:
        hyperobject["engines"] = sorted(str(e) for e in engines)
    if hyperobject:
        data["hyperobject"] = hyperobject

    data["accent"] = accent_for(entry, manifest)
    if provenance:
        data["badge"] = provenance
    return data


def texture_payload(entry: dict[str, Any], manifest: dict[str, Any] | None = None) -> dict[str, Any]:
    """Build the ``hyperobject-texture`` ``data`` block for one cartridge.

    The texture template is FLUX-backed, so its input is a prompt-shaped
    description of the material world the cartridge lives in, plus the same
    accent so card and texture stay in one palette.
    """
    manifest = manifest or {}
    slug = str(entry["slug"])
    domain = str(entry.get("domain") or "") or None

    data: dict[str, Any] = {
        "slug": slug,
        "subject": _clip(_text(entry.get("name")) or slug, 60),
        "accent": accent_for(entry, manifest),
    }
    if domain:
        data["domain"] = domain
    standards = entry.get("standards")
    if isinstance(standards, list) and standards:
        # Standards are what the object physically mates with — the strongest
        # material cue available without rendering geometry.
        data["standards"] = sorted({str(s) for s in standards if str(s).strip()})[:4]
    return data


PAYLOAD_BUILDERS = {"card": card_payload, "texture": texture_payload}


def build_payload(kind: str, entry: dict[str, Any], manifest: dict[str, Any] | None = None) -> dict[str, Any]:
    try:
        builder = PAYLOAD_BUILDERS[kind]
    except KeyError:
        raise CoverageError(f"unknown asset kind {kind!r} (known: {', '.join(ASSET_KINDS)})") from None
    return builder(entry, manifest)


# ──────────────────────────────────────────────────────────────────────────────
# Payload hash — byte-identical to ceq's render_hash
# ──────────────────────────────────────────────────────────────────────────────

def payload_hash(template: str, data: dict[str, Any], template_version: str) -> str:
    """sha256 over ``{"template", "version", "data"}``, ceq's exact recipe.

    Mirrors ceq ``apps/api/src/ceq_api/render/hash.py``. Keep the serializer
    arguments identical (``sort_keys``, compact separators, ``default=str``) —
    any drift silently breaks resume by making every local hash miss.
    """
    payload = {"template": template, "version": template_version, "data": data}
    serialized = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


# ──────────────────────────────────────────────────────────────────────────────
# Sidecar — docs/ceq-coverage.json
# ──────────────────────────────────────────────────────────────────────────────
#
# Schema (``ceq_coverage_v1``):
#
#   {
#     "schema_version": "ceq_coverage_v1",
#     "generated_by": "scripts/dev/ceq_backfill.py",
#     "assets": {
#       "<slug>": {
#         "card":    {"url", "hash", "rendered_at",
#                     "template", "template_version", "payload_hash",
#                     "storage_uri"?, "cached"?},
#         "texture": {...same shape...}
#       }
#     }
#   }
#
# ``hash`` is the content hash ceq returned; ``payload_hash`` is what we
# computed locally from the payload we sent. They are equal whenever ceq's
# template version matches what we hashed against — the driver stores both so a
# mismatch is visible rather than assumed away.

_REQUIRED_ASSET_FIELDS = ("url", "hash", "rendered_at")


def empty_sidecar() -> dict[str, Any]:
    return {
        "schema_version": SIDECAR_SCHEMA_VERSION,
        "generated_by": "scripts/dev/ceq_backfill.py",
        "assets": {},
    }


def load_sidecar(path: Path | None = None) -> dict[str, Any]:
    """Read + validate the sidecar. Absent is fine (nothing backfilled yet).

    Malformed is NOT fine and raises :class:`CoverageError` — the tracker
    deliberately fails CI on a broken sidecar even though it never fails on
    missing coverage. Missing coverage is a backlog; a corrupt index is a bug
    that would let the driver re-mint paid renders it already paid for.
    """
    path = path or SIDECAR_PATH
    if not path.exists():
        return empty_sidecar()
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise CoverageError(f"sidecar is not valid JSON ({path}): {exc}") from exc
    validate_sidecar(raw, path)
    return raw


def validate_sidecar(raw: Any, path: Path | None = None) -> dict[str, Any]:
    """Structural validation of a sidecar document. Returns it on success."""
    where = f" ({path})" if path else ""
    if not isinstance(raw, dict):
        raise CoverageError(f"sidecar must be a JSON object{where}")
    version = raw.get("schema_version")
    if version != SIDECAR_SCHEMA_VERSION:
        raise CoverageError(
            f"sidecar schema_version is {version!r}, expected {SIDECAR_SCHEMA_VERSION!r}{where}"
        )
    assets = raw.get("assets")
    if not isinstance(assets, dict):
        raise CoverageError(f"sidecar has no assets{{}} object{where}")
    for slug, per_slug in assets.items():
        if not isinstance(per_slug, dict):
            raise CoverageError(f"sidecar assets[{slug!r}] must be an object{where}")
        for kind, record in per_slug.items():
            if kind not in ASSET_KINDS:
                raise CoverageError(
                    f"sidecar assets[{slug!r}] has unknown asset kind {kind!r}{where}"
                )
            if not isinstance(record, dict):
                raise CoverageError(f"sidecar assets[{slug!r}][{kind!r}] must be an object{where}")
            missing = [f for f in _REQUIRED_ASSET_FIELDS if not isinstance(record.get(f), str)]
            if missing:
                raise CoverageError(
                    f"sidecar assets[{slug!r}][{kind!r}] missing/non-string "
                    f"{', '.join(missing)}{where}"
                )
    return raw


def serialize_sidecar(sidecar: dict[str, Any]) -> str:
    """Deterministic serialization — sorted keys, 2-space indent, trailing NL.

    The sidecar is committed, so byte-stability across runs is what keeps its
    diffs readable (and keeps a no-op backfill from producing a diff at all).
    """
    ordered = {
        "schema_version": sidecar.get("schema_version", SIDECAR_SCHEMA_VERSION),
        "generated_by": sidecar.get("generated_by", "scripts/dev/ceq_backfill.py"),
        "assets": {
            slug: {kind: dict(sorted(sidecar["assets"][slug][kind].items()))
                   for kind in sorted(sidecar["assets"][slug])}
            for slug in sorted(sidecar.get("assets", {}))
        },
    }
    return json.dumps(ordered, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def write_sidecar(sidecar: dict[str, Any], path: Path | None = None) -> None:
    path = path or SIDECAR_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(serialize_sidecar(sidecar), encoding="utf-8")


def sidecar_record(sidecar: dict[str, Any], slug: str, kind: str) -> dict[str, Any] | None:
    return (sidecar.get("assets", {}).get(slug) or {}).get(kind)


def needs_render(sidecar: dict[str, Any], slug: str, kind: str, expected_payload_hash: str) -> bool:
    """Whether ``(slug, kind)`` still needs a render.

    Skip only when the sidecar already holds a record whose ``payload_hash``
    equals what we would send now. A record without a stored ``payload_hash``
    (hand-written, or from an older writer) is re-rendered rather than trusted —
    ceq's cache makes that cheap and it heals the index.
    """
    record = sidecar_record(sidecar, slug, kind)
    if not record:
        return True
    return record.get("payload_hash") != expected_payload_hash


def upsert_record(sidecar: dict[str, Any], slug: str, kind: str, record: dict[str, Any]) -> None:
    sidecar.setdefault("assets", {}).setdefault(slug, {})[kind] = record
