apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yantra4d

resources:
- namespace.yaml
- yantra4d-backend-deployment.yaml
- yantra4d-backend-service.yaml
- yantra4d-studio-deployment.yaml
- yantra4d-studio-service.yaml
- yantra4d-landing-deployment.yaml
- yantra4d-landing-service.yaml
- yantra4d-admin-deployment.yaml
- yantra4d-admin-service.yaml
- yantra4d-analytics-pvc.yaml
- yantra4d-redis-pvc.yaml
- yantra4d-redis-deployment.yaml
- yantra4d-redis-service.yaml

images:
- digest: sha256:2aa4f3174d4cf3a6ed118774c2faca3046224f9ac74d854917f8d9f35b138724
  name: ghcr.io/madfam-org/yantra4d/admin
  newName: ghcr.io/madfam-org/yantra4d/admin
- digest: sha256:ccb6f596715941c3b33f0088902103362a90d794bdb12ecd747655f6671b7978
  name: ghcr.io/madfam-org/yantra4d/backend
  newName: ghcr.io/madfam-org/yantra4d/backend
- digest: sha256:2ca775d4dd0915fb73b6a274a98471a1136c5ad66e1466c177f51007311bc358
  name: ghcr.io/madfam-org/yantra4d/landing
  newName: ghcr.io/madfam-org/yantra4d/landing
- digest: sha256:9cb8039775321bd7be50d54cd6fd0a08714e5145640c99b3e17c1b4b652385ee
  name: ghcr.io/madfam-org/yantra4d/studio
  newName: ghcr.io/madfam-org/yantra4d/studio
