apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yantra4d

resources:
- namespace.yaml
- yantra4d-backend-deployment.yaml
- yantra4d-backend-service.yaml
- yantra4d-studio-deployment.yaml
- yantra4d-studio-service.yaml
- yantra4d-landing-deployment.yaml
- yantra4d-landing-service.yaml
- yantra4d-admin-deployment.yaml
- yantra4d-admin-service.yaml
- yantra4d-analytics-pvc.yaml
- yantra4d-redis-pvc.yaml
- yantra4d-redis-deployment.yaml
- yantra4d-redis-service.yaml

images:
- digest: sha256:b8eca2ebee3482bceed846b973c8048b4611504d2729ca1a715e0db63112b761
  name: ghcr.io/madfam-org/yantra4d/admin
  newName: ghcr.io/madfam-org/yantra4d/admin
- digest: sha256:30df19cfdb3ff34add66610fa735a4b57e8fc6f6a222c44a02e29439f889324a
  name: ghcr.io/madfam-org/yantra4d/backend
  newName: ghcr.io/madfam-org/yantra4d/backend
- digest: sha256:2cc856f6e848f17c9920b5b3f3b21e90bf0644cd8fba6c308b1c10c8f173f038
  name: ghcr.io/madfam-org/yantra4d/landing
  newName: ghcr.io/madfam-org/yantra4d/landing
- digest: sha256:3bbc9a0b68d33c16049c060b21d714378b4345eefb6108e9d9ff7c56c91530db
  name: ghcr.io/madfam-org/yantra4d/studio
  newName: ghcr.io/madfam-org/yantra4d/studio
